package model;

public enum NotificationType {
    BOOKING_CREATED,
    BOOKING_APPROVED,
    BOOKING_REJECTED,
    TICKET_CREATED,
    TICKET_ASSIGNED,
    TICKET_STATUS_UPDATED,
    TICKET_COMMENT_ADDED,
    TICKET_UPDATED,
    BOOKING_UPDATED,
    BOOKING_CANCELLED,
    USER_REGISTERED,
    LECTURE_SHARED,
    LECTURE_UPDATED,
    LECTURE_CANCELLED,
    STUDENT_BATCH_MATCH,
    ATTENDANCE_SUBMITTED,
    ANNOUNCEMENT_PUBLISHED
}
